/**
 * Manifest-driven asset layer.
 *
 * Components/screens reference assets by **stable id** (e.g. `professional/cleaning-female-01`)
 * and never touch raw file paths or URLs. This resolver turns an id into a usable URL,
 * safely encoding the spaces/parentheses in the source folder names.
 *
 * Source of truth: ./assets.manifest.json (generated by build-asset-manifest.mjs from the
 * repo's root asset folders). Missing ids are reported loudly — they are never silently
 * swapped for a placeholder.
 *
 * The base URL points at the assets' canonical location (the repo's raw GitHub). Call
 * `configureAssets({ baseUrl })` to repoint it (e.g. to a locally-served/bundled copy) later.
 */
import manifestJson from './assets.manifest.json';

export type AssetKind =
  | 'icon'
  | 'icon3d'
  | 'avatar'
  | 'professional'
  | 'professional-card'
  | 'service'
  | 'banner'
  | 'payment'
  | 'flag'
  | 'shape';

export interface AssetEntry {
  /** Real on-disk path, faithful to the repo (may contain spaces/parens). */
  path: string;
  kind: AssetKind;
  /** File extension, lowercase: 'png' | 'svg' | … */
  format: string;
  /** Sub-classification where meaningful (e.g. professional → 'cleaning' | 'doctor' | …). */
  category?: string;
}

export interface AssetManifest {
  $schema: string;
  version: string;
  source: string;
  baseUrl: string;
  kinds: AssetKind[];
  count: number;
  countByKind: Record<string, number>;
  assets: Record<string, AssetEntry>;
}

/** A manifest asset id, e.g. `payment/tamara`. */
export type AssetId = string;

/** An image source object accepted by both react-native `<Image>` and web `<img>`. */
export interface AssetSource {
  uri: string;
}

const manifest = manifestJson as unknown as AssetManifest;

let baseUrl = normalizeBase(manifest.baseUrl);

function normalizeBase(url: string): string {
  return url.endsWith('/') ? url : url + '/';
}

/** Encode each path segment so spaces/parens are URL-safe (slashes preserved). */
function encodePath(path: string): string {
  return path.split('/').map(encodeURIComponent).join('/');
}

export class AssetNotFoundError extends Error {
  constructor(id: string) {
    super(`[assets] unknown asset id: "${id}". Register it in assets.manifest.json — do not fall back to a placeholder.`);
    this.name = 'AssetNotFoundError';
  }
}

// ---- introspection ----

export const assetKinds: readonly AssetKind[] = manifest.kinds;
export const assetCount: number = manifest.count;
export const assetCountByKind: Readonly<Record<string, number>> = manifest.countByKind;

export function assetIds(): AssetId[] {
  return Object.keys(manifest.assets);
}

export function hasAsset(id: AssetId): boolean {
  return Object.prototype.hasOwnProperty.call(manifest.assets, id);
}

export function getAsset(id: AssetId): AssetEntry | undefined {
  return manifest.assets[id];
}

export function assetIdsByKind(kind: AssetKind): AssetId[] {
  return assetIds().filter((id) => manifest.assets[id]?.kind === kind);
}

/** Report which of the requested ids are not in the manifest (for audits — no side effects). */
export function listMissing(ids: AssetId[]): AssetId[] {
  return ids.filter((id) => !hasAsset(id));
}

// ---- resolution ----

/** Point the resolver at a different base (e.g. a locally-served copy). */
export function configureAssets(opts: { baseUrl?: string }): void {
  if (opts.baseUrl) baseUrl = normalizeBase(opts.baseUrl);
}

export function assetBaseUrl(): string {
  return baseUrl;
}

/** Resolve an id to a fully-qualified URL. Throws `AssetNotFoundError` if unknown. */
export function assetUrl(id: AssetId): string {
  const entry = manifest.assets[id];
  if (!entry) throw new AssetNotFoundError(id);
  return baseUrl + encodePath(entry.path);
}

/** Resolve an id to an `<Image>`-ready source. Throws if unknown. */
export function assetSource(id: AssetId): AssetSource {
  return { uri: assetUrl(id) };
}

/** Soft variant: returns `null` (and warns) instead of throwing when an id is unknown. */
export function tryAssetSource(id: AssetId): AssetSource | null {
  if (!hasAsset(id)) {
    console.warn(`[assets] missing asset id: "${id}" — rendering nothing (no placeholder).`);
    return null;
  }
  return { uri: assetUrl(id) };
}
