/**
 * Style Dictionary build for @justlife/tokens.
 *
 * Produces, from the DTCG source in src/:
 *   - dist/css/tokens.css      CSS custom properties (light at :root, dark at [data-theme="dark"])
 *   - generated/light.ts       typed `lightTokens` object (as const)
 *   - generated/dark.ts        typed `darkTokens` object (as const)
 *   - generated/index.ts       themes map + Tokens / ThemeName types
 *
 * The TS files are compiled to dist/ by tsc (see package.json "build").
 */
import StyleDictionary from 'style-dictionary';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(fileURLToPath(import.meta.url));
const typeOf = (t) => t.$type ?? t.type;
const valueOf = (t) => (t.value !== undefined ? t.value : t.$value);

// --- transforms: CSS needs units; TS keeps raw numbers (for React Native) ---
StyleDictionary.registerTransform({
  name: 'dimension/px',
  type: 'value',
  transitive: true,
  filter: (t) => typeOf(t) === 'dimension',
  transform: (t) => {
    const v = valueOf(t);
    return typeof v === 'number' ? `${v}px` : v;
  },
});

StyleDictionary.registerTransform({
  name: 'duration/css',
  type: 'value',
  transitive: true,
  filter: (t) => typeOf(t) === 'duration',
  transform: (t) => {
    const v = valueOf(t);
    return typeof v === 'number' ? `${v}ms` : v;
  },
});

StyleDictionary.registerTransform({
  name: 'cubicBezier/css',
  type: 'value',
  transitive: true,
  filter: (t) => typeOf(t) === 'cubicBezier',
  transform: (t) => {
    const v = valueOf(t);
    return Array.isArray(v) ? `cubic-bezier(${v.join(', ')})` : v;
  },
});

// Figma token names are kebab-case (e.g. `bg-hover`); camelCase them for
// ergonomic dot-access in TS (`t.btn.primary.bgHover`). CSS keeps kebab.
const camel = (seg) =>
  seg.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase()).replace(/-/g, '');

// --- format: typed, nested, `as const` object for first-class TS autocomplete ---
StyleDictionary.registerFormat({
  name: 'javascript/as-const',
  format: ({ dictionary, file }) => {
    const exportName = file?.options?.exportName ?? 'tokens';
    const tree = {};
    for (const token of dictionary.allTokens) {
      let node = tree;
      const segs = token.path.map(camel);
      for (let i = 0; i < segs.length; i++) {
        const seg = segs[i];
        if (i === segs.length - 1) node[seg] = valueOf(token);
        else node = node[seg] ?? (node[seg] = {});
      }
    }
    return (
      '// Auto-generated by @justlife/tokens. Do not edit by hand.\n' +
      `export const ${exportName} = ${JSON.stringify(tree, null, 2)} as const;\n`
    );
  },
});

const BASE = ['src/primitive/*.json', 'src/semantic/*.json'];

function makeSD({ themeFile, cssDest, cssSelector, cssColorOnly, tsDest, tsExport }) {
  return new StyleDictionary({
    source: [...BASE, themeFile],
    log: { verbosity: 'silent' },
    platforms: {
      css: {
        transforms: ['attribute/cti', 'name/kebab', 'dimension/px', 'duration/css', 'cubicBezier/css'],
        buildPath: 'dist/css/',
        files: [
          {
            destination: cssDest,
            format: 'css/variables',
            options: { selector: cssSelector, outputReferences: false },
            filter: (t) => {
              const type = typeOf(t);
              if (type === 'typography' || type === 'shadow') return false; // composites -> TS only
              // Dark layer only overrides theme colours, not the mode-agnostic
              // primitive `color` ramp.
              if (cssColorOnly) return type === 'color' && t.path[0] !== 'color';
              return true;
            },
          },
        ],
      },
      ts: {
        transforms: ['attribute/cti'],
        buildPath: 'generated/',
        files: [{ destination: tsDest, format: 'javascript/as-const', options: { exportName: tsExport } }],
      },
    },
  });
}

await fs.rm(path.join(root, 'dist'), { recursive: true, force: true });
await fs.rm(path.join(root, 'generated'), { recursive: true, force: true });

const light = makeSD({
  themeFile: 'src/themes/light.json',
  cssDest: '_light.css',
  cssSelector: ':root',
  cssColorOnly: false,
  tsDest: 'light.ts',
  tsExport: 'lightTokens',
});
const dark = makeSD({
  themeFile: 'src/themes/dark.json',
  cssDest: '_dark.css',
  cssSelector: ':root[data-theme="dark"]',
  cssColorOnly: true,
  tsDest: 'dark.ts',
  tsExport: 'darkTokens',
});

await light.buildAllPlatforms();
await dark.buildAllPlatforms();

// Combine the two CSS layers into one file.
const cssDir = path.join(root, 'dist', 'css');
const lightCss = await fs.readFile(path.join(cssDir, '_light.css'), 'utf8');
const darkCss = await fs.readFile(path.join(cssDir, '_dark.css'), 'utf8');
const banner =
  '/**\n * Justlife Design System — design tokens (CSS custom properties).\n * Auto-generated. Do not edit by hand.\n */\n';
await fs.writeFile(path.join(cssDir, 'tokens.css'), `${banner}${lightCss}\n${darkCss}`);
await fs.rm(path.join(cssDir, '_light.css'), { force: true });
await fs.rm(path.join(cssDir, '_dark.css'), { force: true });

// Compose the TS entrypoint. Leaf literal types are widened so that the light
// and dark token trees share one structural `Tokens` type (their literal values
// differ, but their shape is identical).
const indexTs = `// Auto-generated by @justlife/tokens. Do not edit by hand.
import { lightTokens } from './light.js';
import { darkTokens } from './dark.js';

type Widen<T> = T extends string
  ? string
  : T extends number
    ? number
    : T extends boolean
      ? boolean
      : { readonly [K in keyof T]: Widen<T[K]> };

export type ThemeName = 'light' | 'dark';
export type Tokens = Widen<typeof lightTokens>;

export const themes: Record<ThemeName, Tokens> = { light: lightTokens, dark: darkTokens };
export const defaultThemeName: ThemeName = 'light';
export { lightTokens, darkTokens };
`;
await fs.writeFile(path.join(root, 'generated', 'index.ts'), indexTs);

console.log('✓ @justlife/tokens built: dist/css/tokens.css + generated/{light,dark,index}.ts');
